version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    stdin_open: true
